system:
    path: c:/Test
    exts: ['.mkv','.avi']
    maxretries: 3

bayfiles:
    username: dvl
    password: 123456
# for next release

database:
    engine: mysql       # only mysql suported now
    host: localhost
    user: root
    password: deadpool
    dbname: files